NAME RRP
OBJSENSE MAX
ROWS
 N  OBJ
 E  R0      
 E  R1      
 E  R2      
 E  R3      
 E  R4      
 E  R5      
 E  R6      
 E  R7      
 E  R8      
 E  R9      
 E  R10     
 E  R11     
 E  R12     
 E  R13     
 E  R14     
 E  R15     
 E  R16     
 E  R17     
 E  R18     
 E  R19     
 E  R20     
 E  R21     
 E  R22     
 E  R23     
 E  R24     
 E  R25     
 E  R26     
 E  R27     
 E  R28     
 E  R29     
 E  R30     
 E  R31     
 L  R32     
 L  R33     
 L  R34     
 L  R35     
 E  R36     
 E  R37     
 E  R38     
 E  R39     
 E  R40     
 L  R41     
 L  R42     
 L  R43     
 L  R44     
 L  R45     
 L  R46     
 L  R47     
 L  R48     
 L  R49     
 L  R50     
 L  R51     
 L  R52     
 L  R53     
 L  R54     
 L  R55     
 L  R56     
 L  R57     
 L  R58     
 L  R59     
 L  R60     
 L  R61     
 L  R62     
 L  R63     
 L  R64     
 L  R65     
 L  R66     
 L  R67     
 L  R68     
 L  R69     
 L  R70     
 L  R71     
 L  R72     
 L  R73     
 L  R74     
 L  R75     
 L  R76     
 L  R77     
 L  R78     
 L  R79     
 L  R80     
 L  R81     
 L  R82     
 L  R83     
 L  R84     
 L  R85     
 L  R86     
 L  R87     
 L  R88     
 L  R89     
 L  R90     
 L  R91     
 L  R92     
 L  R93     
 L  R94     
 L  R95     
 L  R96     
 L  R97     
 L  R98     
 L  R99     
 L  R100    
 L  R101    
 L  R102    
 L  R103    
 L  R104    
 L  R105    
 L  R106    
 L  R107    
 L  R108    
 L  R109    
 L  R110    
 L  R111    
 L  R112    
 L  R113    
 L  R114    
 L  R115    
 L  R116    
 L  R117    
 L  R118    
 L  R119    
 L  R120    
 L  R121    
 L  R122    
 L  R123    
 L  R124    
 L  R125    
 L  R126    
 L  R127    
 L  R128    
 L  R129    
 L  R130    
 L  R131    
 L  R132    
 L  R133    
 L  R134    
 L  R135    
 L  R136    
 L  R137    
 L  R138    
 G  R139    
 G  R140    
 G  R141    
 G  R142    
 G  R143    
 G  R144    
 G  R145    
 G  R146    
 G  R147    
 G  R148    
 G  R149    
 G  R150    
 G  R151    
 G  R152    
 G  R153    
 G  R154    
 G  R155    
 G  R156    
 G  R157    
 G  R158    
 G  R159    
 G  R160    
 G  R161    
 G  R162    
 G  R163    
 G  R164    
 G  R165    
 G  R166    
 G  R167    
 G  R168    
 G  R169    
 G  R170    
 G  R171    
 G  R172    
 G  R173    
 G  R174    
 G  R175    
 G  R176    
 G  R177    
 G  R178    
 G  R179    
 G  R180    
 G  R181    
 G  R182    
 G  R183    
 G  R184    
 G  R185    
 G  R186    
 G  R187    
 G  R188    
 G  R189    
 G  R190    
 G  R191    
 G  R192    
 G  R193    
 G  R194    
 G  R195    
 G  R196    
 G  R197    
 G  R198    
 G  R199    
 G  R200    
 G  R201    
 G  R202    
 G  R203    
 G  R204    
 G  R205    
 G  R206    
 G  R207    
 G  R208    
 G  R209    
 G  R210    
 L  R211    
 L  R212    
 L  R213    
 L  R214    
 L  R215    
 L  R216    
 L  R217    
 L  R218    
 L  R219    
 L  R220    
 L  R221    
 L  R222    
 L  R223    
 G  R224    
 G  R225    
 G  R226    
 G  R227    
 G  R228    
 G  R229    
 G  R230    
 G  R231    
 G  R232    
 G  R233    
 G  R234    
 G  R235    
 G  R236    
 L  R237    
 L  R238    
 G  R239    
 G  R240    
 G  R241    
 G  R242    
 L  R243    
 L  R244    
 G  R245    
 L  R246    
 L  R247    
 L  R248    
 L  R249    
 L  R250    
 L  R251    
 L  R252    
 L  R253    
 L  R254    
 L  R255    
 L  R256    
 L  R257    
 L  R258    
 L  R259    
 L  R260    
 G  R261    
 G  R262    
 L  R263    
COLUMNS
    MARKER    'MARKER'                 'INTORG'
    x_kimjn[0,1,17,1,17]  OBJ       0
    x_kimjn[0,1,17,1,0]  OBJ       0
    x_kimjn[0,1,17,2,1]  R2        -1
    x_kimjn[0,1,17,2,1]  R4        1
    x_kimjn[0,1,17,2,1]  R19       1
    x_kimjn[0,1,17,2,1]  R37       1
    x_kimjn[0,1,17,2,1]  R39       1
    x_kimjn[0,1,17,2,1]  R67       172.5
    x_kimjn[0,1,17,2,1]  R139      -172.5
    x_kimjn[0,1,17,2,2]  R2        -1
    x_kimjn[0,1,17,2,2]  R5        1
    x_kimjn[0,1,17,2,2]  R20       1
    x_kimjn[0,1,17,2,2]  R37       1
    x_kimjn[0,1,17,2,2]  R39       1
    x_kimjn[0,1,17,2,2]  R68       172.5
    x_kimjn[0,1,17,2,2]  R140      -172.5
    x_kimjn[0,1,17,2,9]  R2        -1
    x_kimjn[0,1,17,2,9]  R6        1
    x_kimjn[0,1,17,2,9]  R21       1
    x_kimjn[0,1,17,2,9]  R37       1
    x_kimjn[0,1,17,2,9]  R39       1
    x_kimjn[0,1,17,2,9]  R69       172.5
    x_kimjn[0,1,17,2,9]  R141      -172.5
    x_kimjn[0,1,17,2,12]  R2        -1
    x_kimjn[0,1,17,2,12]  R7        1
    x_kimjn[0,1,17,2,12]  R22       1
    x_kimjn[0,1,17,2,12]  R37       1
    x_kimjn[0,1,17,2,12]  R39       1
    x_kimjn[0,1,17,2,12]  R70       172.5
    x_kimjn[0,1,17,2,12]  R142      -172.5
    x_kimjn[0,1,17,2,10]  R2        -1
    x_kimjn[0,1,17,2,10]  R8        1
    x_kimjn[0,1,17,2,10]  R23       1
    x_kimjn[0,1,17,2,10]  R37       1
    x_kimjn[0,1,17,2,10]  R39       1
    x_kimjn[0,1,17,2,10]  R71       172.5
    x_kimjn[0,1,17,2,10]  R143      -172.5
    x_kimjn[0,1,17,2,5]  R2        -1
    x_kimjn[0,1,17,2,5]  R9        1
    x_kimjn[0,1,17,2,5]  R24       1
    x_kimjn[0,1,17,2,5]  R37       1
    x_kimjn[0,1,17,2,5]  R39       1
    x_kimjn[0,1,17,2,5]  R72       172.5
    x_kimjn[0,1,17,2,5]  R144      -172.5
    x_kimjn[0,1,17,2,6]  R2        -1
    x_kimjn[0,1,17,2,6]  R10       1
    x_kimjn[0,1,17,2,6]  R25       1
    x_kimjn[0,1,17,2,6]  R37       1
    x_kimjn[0,1,17,2,6]  R39       1
    x_kimjn[0,1,17,2,6]  R73       172.5
    x_kimjn[0,1,17,2,6]  R145      -172.5
    x_kimjn[0,1,17,2,7]  R2        -1
    x_kimjn[0,1,17,2,7]  R11       1
    x_kimjn[0,1,17,2,7]  R26       1
    x_kimjn[0,1,17,2,7]  R37       1
    x_kimjn[0,1,17,2,7]  R39       1
    x_kimjn[0,1,17,2,7]  R74       172.5
    x_kimjn[0,1,17,2,7]  R146      -172.5
    x_kimjn[0,1,17,2,8]  R2        -1
    x_kimjn[0,1,17,2,8]  R12       1
    x_kimjn[0,1,17,2,8]  R27       1
    x_kimjn[0,1,17,2,8]  R37       1
    x_kimjn[0,1,17,2,8]  R39       1
    x_kimjn[0,1,17,2,8]  R75       172.5
    x_kimjn[0,1,17,2,8]  R147      -172.5
    x_kimjn[0,1,17,2,13]  R2        -1
    x_kimjn[0,1,17,2,13]  R13       1
    x_kimjn[0,1,17,2,13]  R28       1
    x_kimjn[0,1,17,2,13]  R37       1
    x_kimjn[0,1,17,2,13]  R39       1
    x_kimjn[0,1,17,2,13]  R76       172.5
    x_kimjn[0,1,17,2,13]  R148      -172.5
    x_kimjn[0,1,17,2,0]  R2        -1
    x_kimjn[0,1,17,2,0]  R14       1
    x_kimjn[0,1,17,2,0]  R29       1
    x_kimjn[0,1,17,2,0]  R39       1
    x_kimjn[0,1,17,2,0]  R77       172.5
    x_kimjn[0,1,17,2,0]  R149      -172.5
    x_kimjn[0,1,17,3,0]  R2        -1
    x_kimjn[0,1,17,3,0]  R15       -1
    x_kimjn[0,1,17,3,0]  R39       2
    x_kimjn[0,1,17,3,0]  R78       172.5
    x_kimjn[0,1,17,3,0]  R150      -172.5
    x_kimjn[0,1,17,4,0]  R2        -1
    x_kimjn[0,1,17,4,0]  R16       -1
    x_kimjn[0,1,17,4,0]  R39       1
    x_kimjn[0,1,17,4,0]  R40       1
    x_kimjn[0,1,17,4,0]  R79       172.5
    x_kimjn[0,1,17,4,0]  R151      -172.5
    x_kimjn[0,1,0,1,17]  OBJ       0
    x_kimjn[0,1,0,1,0]  OBJ       0
    x_kimjn[0,1,0,2,1]  R3        -1
    x_kimjn[0,1,0,2,1]  R4        1
    x_kimjn[0,1,0,2,1]  R19       1
    x_kimjn[0,1,0,2,1]  R37       1
    x_kimjn[0,1,0,2,1]  R80       172.5
    x_kimjn[0,1,0,2,1]  R152      -172.5
    x_kimjn[0,1,0,2,2]  R3        -1
    x_kimjn[0,1,0,2,2]  R5        1
    x_kimjn[0,1,0,2,2]  R20       1
    x_kimjn[0,1,0,2,2]  R37       1
    x_kimjn[0,1,0,2,2]  R81       172.5
    x_kimjn[0,1,0,2,2]  R153      -172.5
    x_kimjn[0,1,0,2,9]  R3        -1
    x_kimjn[0,1,0,2,9]  R6        1
    x_kimjn[0,1,0,2,9]  R21       1
    x_kimjn[0,1,0,2,9]  R37       1
    x_kimjn[0,1,0,2,9]  R82       172.5
    x_kimjn[0,1,0,2,9]  R154      -172.5
    x_kimjn[0,1,0,2,12]  R3        -1
    x_kimjn[0,1,0,2,12]  R7        1
    x_kimjn[0,1,0,2,12]  R22       1
    x_kimjn[0,1,0,2,12]  R37       1
    x_kimjn[0,1,0,2,12]  R83       172.5
    x_kimjn[0,1,0,2,12]  R155      -172.5
    x_kimjn[0,1,0,2,10]  R3        -1
    x_kimjn[0,1,0,2,10]  R8        1
    x_kimjn[0,1,0,2,10]  R23       1
    x_kimjn[0,1,0,2,10]  R37       1
    x_kimjn[0,1,0,2,10]  R84       172.5
    x_kimjn[0,1,0,2,10]  R156      -172.5
    x_kimjn[0,1,0,2,5]  R3        -1
    x_kimjn[0,1,0,2,5]  R9        1
    x_kimjn[0,1,0,2,5]  R24       1
    x_kimjn[0,1,0,2,5]  R37       1
    x_kimjn[0,1,0,2,5]  R85       172.5
    x_kimjn[0,1,0,2,5]  R157      -172.5
    x_kimjn[0,1,0,2,6]  R3        -1
    x_kimjn[0,1,0,2,6]  R10       1
    x_kimjn[0,1,0,2,6]  R25       1
    x_kimjn[0,1,0,2,6]  R37       1
    x_kimjn[0,1,0,2,6]  R86       172.5
    x_kimjn[0,1,0,2,6]  R158      -172.5
    x_kimjn[0,1,0,2,7]  R3        -1
    x_kimjn[0,1,0,2,7]  R11       1
    x_kimjn[0,1,0,2,7]  R26       1
    x_kimjn[0,1,0,2,7]  R37       1
    x_kimjn[0,1,0,2,7]  R87       172.5
    x_kimjn[0,1,0,2,7]  R159      -172.5
    x_kimjn[0,1,0,2,8]  R3        -1
    x_kimjn[0,1,0,2,8]  R12       1
    x_kimjn[0,1,0,2,8]  R27       1
    x_kimjn[0,1,0,2,8]  R37       1
    x_kimjn[0,1,0,2,8]  R88       172.5
    x_kimjn[0,1,0,2,8]  R160      -172.5
    x_kimjn[0,1,0,2,13]  R3        -1
    x_kimjn[0,1,0,2,13]  R13       1
    x_kimjn[0,1,0,2,13]  R28       1
    x_kimjn[0,1,0,2,13]  R37       1
    x_kimjn[0,1,0,2,13]  R89       172.5
    x_kimjn[0,1,0,2,13]  R161      -172.5
    x_kimjn[0,1,0,2,0]  R3        -1
    x_kimjn[0,1,0,2,0]  R14       1
    x_kimjn[0,1,0,2,0]  R29       1
    x_kimjn[0,1,0,2,0]  R90       172.5
    x_kimjn[0,1,0,2,0]  R162      -172.5
    x_kimjn[0,1,0,3,0]  R3        -1
    x_kimjn[0,1,0,3,0]  R15       -1
    x_kimjn[0,1,0,3,0]  R39       1
    x_kimjn[0,1,0,3,0]  R91       172.5
    x_kimjn[0,1,0,3,0]  R163      -172.5
    x_kimjn[0,1,0,4,0]  R3        -1
    x_kimjn[0,1,0,4,0]  R16       -1
    x_kimjn[0,1,0,4,0]  R40       1
    x_kimjn[0,1,0,4,0]  R92       172.5
    x_kimjn[0,1,0,4,0]  R164      -172.5
    x_kimjn[0,2,1,1,17]  R2        1
    x_kimjn[0,2,1,1,17]  R4        -1
    x_kimjn[0,2,1,1,17]  R17       1
    x_kimjn[0,2,1,1,17]  R36       1
    x_kimjn[0,2,1,1,17]  R40       1
    x_kimjn[0,2,1,1,17]  R93       172.5
    x_kimjn[0,2,1,1,17]  R165      -172.5
    x_kimjn[0,2,1,1,0]  R3        1
    x_kimjn[0,2,1,1,0]  R4        -1
    x_kimjn[0,2,1,1,0]  R18       1
    x_kimjn[0,2,1,1,0]  R40       1
    x_kimjn[0,2,1,1,0]  R94       172.5
    x_kimjn[0,2,1,1,0]  R166      -172.5
    x_kimjn[0,2,1,2,1]  OBJ       0
    x_kimjn[0,2,1,2,2]  OBJ       0
    x_kimjn[0,2,1,2,9]  OBJ       0
    x_kimjn[0,2,1,2,12]  OBJ       0
    x_kimjn[0,2,1,2,10]  OBJ       0
    x_kimjn[0,2,1,2,5]  OBJ       0
    x_kimjn[0,2,1,2,6]  OBJ       0
    x_kimjn[0,2,1,2,7]  OBJ       0
    x_kimjn[0,2,1,2,8]  OBJ       0
    x_kimjn[0,2,1,2,13]  OBJ       0
    x_kimjn[0,2,1,2,0]  OBJ       0
    x_kimjn[0,2,1,3,0]  R4        -1
    x_kimjn[0,2,1,3,0]  R15       -1
    x_kimjn[0,2,1,3,0]  R39       1
    x_kimjn[0,2,1,3,0]  R40       1
    x_kimjn[0,2,1,3,0]  R95       172.5
    x_kimjn[0,2,1,3,0]  R167      -172.5
    x_kimjn[0,2,1,4,0]  R4        -1
    x_kimjn[0,2,1,4,0]  R16       -1
    x_kimjn[0,2,1,4,0]  R40       2
    x_kimjn[0,2,1,4,0]  R96       172.5
    x_kimjn[0,2,1,4,0]  R168      -172.5
    x_kimjn[0,2,2,1,17]  R2        1
    x_kimjn[0,2,2,1,17]  R5        -1
    x_kimjn[0,2,2,1,17]  R17       1
    x_kimjn[0,2,2,1,17]  R36       1
    x_kimjn[0,2,2,1,17]  R40       1
    x_kimjn[0,2,2,1,17]  R97       172.5
    x_kimjn[0,2,2,1,17]  R169      -172.5
    x_kimjn[0,2,2,1,0]  R3        1
    x_kimjn[0,2,2,1,0]  R5        -1
    x_kimjn[0,2,2,1,0]  R18       1
    x_kimjn[0,2,2,1,0]  R40       1
    x_kimjn[0,2,2,1,0]  R98       172.5
    x_kimjn[0,2,2,1,0]  R170      -172.5
    x_kimjn[0,2,2,2,1]  OBJ       0
    x_kimjn[0,2,2,2,2]  OBJ       0
    x_kimjn[0,2,2,2,9]  OBJ       0
    x_kimjn[0,2,2,2,12]  OBJ       0
    x_kimjn[0,2,2,2,10]  OBJ       0
    x_kimjn[0,2,2,2,5]  OBJ       0
    x_kimjn[0,2,2,2,6]  OBJ       0
    x_kimjn[0,2,2,2,7]  OBJ       0
    x_kimjn[0,2,2,2,8]  OBJ       0
    x_kimjn[0,2,2,2,13]  OBJ       0
    x_kimjn[0,2,2,2,0]  OBJ       0
    x_kimjn[0,2,2,3,0]  R5        -1
    x_kimjn[0,2,2,3,0]  R15       -1
    x_kimjn[0,2,2,3,0]  R39       1
    x_kimjn[0,2,2,3,0]  R40       1
    x_kimjn[0,2,2,3,0]  R99       172.5
    x_kimjn[0,2,2,3,0]  R171      -172.5
    x_kimjn[0,2,2,4,0]  R5        -1
    x_kimjn[0,2,2,4,0]  R16       -1
    x_kimjn[0,2,2,4,0]  R40       2
    x_kimjn[0,2,2,4,0]  R100      172.5
    x_kimjn[0,2,2,4,0]  R172      -172.5
    x_kimjn[0,2,9,1,17]  R2        1
    x_kimjn[0,2,9,1,17]  R6        -1
    x_kimjn[0,2,9,1,17]  R17       1
    x_kimjn[0,2,9,1,17]  R36       1
    x_kimjn[0,2,9,1,17]  R40       1
    x_kimjn[0,2,9,1,17]  R101      172.5
    x_kimjn[0,2,9,1,17]  R173      -172.5
    x_kimjn[0,2,9,1,0]  R3        1
    x_kimjn[0,2,9,1,0]  R6        -1
    x_kimjn[0,2,9,1,0]  R18       1
    x_kimjn[0,2,9,1,0]  R40       1
    x_kimjn[0,2,9,1,0]  R102      172.5
    x_kimjn[0,2,9,1,0]  R174      -172.5
    x_kimjn[0,2,9,2,1]  OBJ       0
    x_kimjn[0,2,9,2,2]  OBJ       0
    x_kimjn[0,2,9,2,9]  OBJ       0
    x_kimjn[0,2,9,2,12]  OBJ       0
    x_kimjn[0,2,9,2,10]  OBJ       0
    x_kimjn[0,2,9,2,5]  OBJ       0
    x_kimjn[0,2,9,2,6]  OBJ       0
    x_kimjn[0,2,9,2,7]  OBJ       0
    x_kimjn[0,2,9,2,8]  OBJ       0
    x_kimjn[0,2,9,2,13]  OBJ       0
    x_kimjn[0,2,9,2,0]  OBJ       0
    x_kimjn[0,2,9,3,0]  R6        -1
    x_kimjn[0,2,9,3,0]  R15       -1
    x_kimjn[0,2,9,3,0]  R39       1
    x_kimjn[0,2,9,3,0]  R40       1
    x_kimjn[0,2,9,3,0]  R103      172.5
    x_kimjn[0,2,9,3,0]  R175      -172.5
    x_kimjn[0,2,9,4,0]  R6        -1
    x_kimjn[0,2,9,4,0]  R16       -1
    x_kimjn[0,2,9,4,0]  R40       2
    x_kimjn[0,2,9,4,0]  R104      172.5
    x_kimjn[0,2,9,4,0]  R176      -172.5
    x_kimjn[0,2,12,1,17]  R2        1
    x_kimjn[0,2,12,1,17]  R7        -1
    x_kimjn[0,2,12,1,17]  R17       1
    x_kimjn[0,2,12,1,17]  R36       1
    x_kimjn[0,2,12,1,17]  R40       1
    x_kimjn[0,2,12,1,17]  R105      172.5
    x_kimjn[0,2,12,1,17]  R177      -172.5
    x_kimjn[0,2,12,1,0]  R3        1
    x_kimjn[0,2,12,1,0]  R7        -1
    x_kimjn[0,2,12,1,0]  R18       1
    x_kimjn[0,2,12,1,0]  R40       1
    x_kimjn[0,2,12,1,0]  R106      172.5
    x_kimjn[0,2,12,1,0]  R178      -172.5
    x_kimjn[0,2,12,2,1]  OBJ       0
    x_kimjn[0,2,12,2,2]  OBJ       0
    x_kimjn[0,2,12,2,9]  OBJ       0
    x_kimjn[0,2,12,2,12]  OBJ       0
    x_kimjn[0,2,12,2,10]  OBJ       0
    x_kimjn[0,2,12,2,5]  OBJ       0
    x_kimjn[0,2,12,2,6]  OBJ       0
    x_kimjn[0,2,12,2,7]  OBJ       0
    x_kimjn[0,2,12,2,8]  OBJ       0
    x_kimjn[0,2,12,2,13]  OBJ       0
    x_kimjn[0,2,12,2,0]  OBJ       0
    x_kimjn[0,2,12,3,0]  R7        -1
    x_kimjn[0,2,12,3,0]  R15       -1
    x_kimjn[0,2,12,3,0]  R39       1
    x_kimjn[0,2,12,3,0]  R40       1
    x_kimjn[0,2,12,3,0]  R107      172.5
    x_kimjn[0,2,12,3,0]  R179      -172.5
    x_kimjn[0,2,12,4,0]  R7        -1
    x_kimjn[0,2,12,4,0]  R16       -1
    x_kimjn[0,2,12,4,0]  R40       2
    x_kimjn[0,2,12,4,0]  R108      172.5
    x_kimjn[0,2,12,4,0]  R180      -172.5
    x_kimjn[0,2,10,1,17]  R2        1
    x_kimjn[0,2,10,1,17]  R8        -1
    x_kimjn[0,2,10,1,17]  R17       1
    x_kimjn[0,2,10,1,17]  R36       1
    x_kimjn[0,2,10,1,17]  R40       1
    x_kimjn[0,2,10,1,17]  R109      172.5
    x_kimjn[0,2,10,1,17]  R181      -172.5
    x_kimjn[0,2,10,1,0]  R3        1
    x_kimjn[0,2,10,1,0]  R8        -1
    x_kimjn[0,2,10,1,0]  R18       1
    x_kimjn[0,2,10,1,0]  R40       1
    x_kimjn[0,2,10,1,0]  R110      172.5
    x_kimjn[0,2,10,1,0]  R182      -172.5
    x_kimjn[0,2,10,2,1]  OBJ       0
    x_kimjn[0,2,10,2,2]  OBJ       0
    x_kimjn[0,2,10,2,9]  OBJ       0
    x_kimjn[0,2,10,2,12]  OBJ       0
    x_kimjn[0,2,10,2,10]  OBJ       0
    x_kimjn[0,2,10,2,5]  OBJ       0
    x_kimjn[0,2,10,2,6]  OBJ       0
    x_kimjn[0,2,10,2,7]  OBJ       0
    x_kimjn[0,2,10,2,8]  OBJ       0
    x_kimjn[0,2,10,2,13]  OBJ       0
    x_kimjn[0,2,10,2,0]  OBJ       0
    x_kimjn[0,2,10,3,0]  R8        -1
    x_kimjn[0,2,10,3,0]  R15       -1
    x_kimjn[0,2,10,3,0]  R39       1
    x_kimjn[0,2,10,3,0]  R40       1
    x_kimjn[0,2,10,3,0]  R111      172.5
    x_kimjn[0,2,10,3,0]  R183      -172.5
    x_kimjn[0,2,10,4,0]  R8        -1
    x_kimjn[0,2,10,4,0]  R16       -1
    x_kimjn[0,2,10,4,0]  R40       2
    x_kimjn[0,2,10,4,0]  R112      172.5
    x_kimjn[0,2,10,4,0]  R184      -172.5
    x_kimjn[0,2,5,1,17]  R2        1
    x_kimjn[0,2,5,1,17]  R9        -1
    x_kimjn[0,2,5,1,17]  R17       1
    x_kimjn[0,2,5,1,17]  R36       1
    x_kimjn[0,2,5,1,17]  R40       1
    x_kimjn[0,2,5,1,17]  R113      172.5
    x_kimjn[0,2,5,1,17]  R185      -172.5
    x_kimjn[0,2,5,1,0]  R3        1
    x_kimjn[0,2,5,1,0]  R9        -1
    x_kimjn[0,2,5,1,0]  R18       1
    x_kimjn[0,2,5,1,0]  R40       1
    x_kimjn[0,2,5,1,0]  R114      172.5
    x_kimjn[0,2,5,1,0]  R186      -172.5
    x_kimjn[0,2,5,2,1]  OBJ       0
    x_kimjn[0,2,5,2,2]  OBJ       0
    x_kimjn[0,2,5,2,9]  OBJ       0
    x_kimjn[0,2,5,2,12]  OBJ       0
    x_kimjn[0,2,5,2,10]  OBJ       0
    x_kimjn[0,2,5,2,5]  OBJ       0
    x_kimjn[0,2,5,2,6]  OBJ       0
    x_kimjn[0,2,5,2,7]  OBJ       0
    x_kimjn[0,2,5,2,8]  OBJ       0
    x_kimjn[0,2,5,2,13]  OBJ       0
    x_kimjn[0,2,5,2,0]  OBJ       0
    x_kimjn[0,2,5,3,0]  R9        -1
    x_kimjn[0,2,5,3,0]  R15       -1
    x_kimjn[0,2,5,3,0]  R39       1
    x_kimjn[0,2,5,3,0]  R40       1
    x_kimjn[0,2,5,3,0]  R115      172.5
    x_kimjn[0,2,5,3,0]  R187      -172.5
    x_kimjn[0,2,5,4,0]  R9        -1
    x_kimjn[0,2,5,4,0]  R16       -1
    x_kimjn[0,2,5,4,0]  R40       2
    x_kimjn[0,2,5,4,0]  R116      172.5
    x_kimjn[0,2,5,4,0]  R188      -172.5
    x_kimjn[0,2,6,1,17]  R2        1
    x_kimjn[0,2,6,1,17]  R10       -1
    x_kimjn[0,2,6,1,17]  R17       1
    x_kimjn[0,2,6,1,17]  R36       1
    x_kimjn[0,2,6,1,17]  R40       1
    x_kimjn[0,2,6,1,17]  R117      172.5
    x_kimjn[0,2,6,1,17]  R189      -172.5
    x_kimjn[0,2,6,1,0]  R3        1
    x_kimjn[0,2,6,1,0]  R10       -1
    x_kimjn[0,2,6,1,0]  R18       1
    x_kimjn[0,2,6,1,0]  R40       1
    x_kimjn[0,2,6,1,0]  R118      172.5
    x_kimjn[0,2,6,1,0]  R190      -172.5
    x_kimjn[0,2,6,2,1]  OBJ       0
    x_kimjn[0,2,6,2,2]  OBJ       0
    x_kimjn[0,2,6,2,9]  OBJ       0
    x_kimjn[0,2,6,2,12]  OBJ       0
    x_kimjn[0,2,6,2,10]  OBJ       0
    x_kimjn[0,2,6,2,5]  OBJ       0
    x_kimjn[0,2,6,2,6]  OBJ       0
    x_kimjn[0,2,6,2,7]  OBJ       0
    x_kimjn[0,2,6,2,8]  OBJ       0
    x_kimjn[0,2,6,2,13]  OBJ       0
    x_kimjn[0,2,6,2,0]  OBJ       0
    x_kimjn[0,2,6,3,0]  R10       -1
    x_kimjn[0,2,6,3,0]  R15       -1
    x_kimjn[0,2,6,3,0]  R39       1
    x_kimjn[0,2,6,3,0]  R40       1
    x_kimjn[0,2,6,3,0]  R119      172.5
    x_kimjn[0,2,6,3,0]  R191      -172.5
    x_kimjn[0,2,6,4,0]  R10       -1
    x_kimjn[0,2,6,4,0]  R16       -1
    x_kimjn[0,2,6,4,0]  R40       2
    x_kimjn[0,2,6,4,0]  R120      172.5
    x_kimjn[0,2,6,4,0]  R192      -172.5
    x_kimjn[0,2,7,1,17]  R2        1
    x_kimjn[0,2,7,1,17]  R11       -1
    x_kimjn[0,2,7,1,17]  R17       1
    x_kimjn[0,2,7,1,17]  R36       1
    x_kimjn[0,2,7,1,17]  R40       1
    x_kimjn[0,2,7,1,17]  R121      172.5
    x_kimjn[0,2,7,1,17]  R193      -172.5
    x_kimjn[0,2,7,1,0]  R3        1
    x_kimjn[0,2,7,1,0]  R11       -1
    x_kimjn[0,2,7,1,0]  R18       1
    x_kimjn[0,2,7,1,0]  R40       1
    x_kimjn[0,2,7,1,0]  R122      172.5
    x_kimjn[0,2,7,1,0]  R194      -172.5
    x_kimjn[0,2,7,2,1]  OBJ       0
    x_kimjn[0,2,7,2,2]  OBJ       0
    x_kimjn[0,2,7,2,9]  OBJ       0
    x_kimjn[0,2,7,2,12]  OBJ       0
    x_kimjn[0,2,7,2,10]  OBJ       0
    x_kimjn[0,2,7,2,5]  OBJ       0
    x_kimjn[0,2,7,2,6]  OBJ       0
    x_kimjn[0,2,7,2,7]  OBJ       0
    x_kimjn[0,2,7,2,8]  OBJ       0
    x_kimjn[0,2,7,2,13]  OBJ       0
    x_kimjn[0,2,7,2,0]  OBJ       0
    x_kimjn[0,2,7,3,0]  R11       -1
    x_kimjn[0,2,7,3,0]  R15       -1
    x_kimjn[0,2,7,3,0]  R39       1
    x_kimjn[0,2,7,3,0]  R40       1
    x_kimjn[0,2,7,3,0]  R123      172.5
    x_kimjn[0,2,7,3,0]  R195      -172.5
    x_kimjn[0,2,7,4,0]  R11       -1
    x_kimjn[0,2,7,4,0]  R16       -1
    x_kimjn[0,2,7,4,0]  R40       2
    x_kimjn[0,2,7,4,0]  R124      172.5
    x_kimjn[0,2,7,4,0]  R196      -172.5
    x_kimjn[0,2,8,1,17]  R2        1
    x_kimjn[0,2,8,1,17]  R12       -1
    x_kimjn[0,2,8,1,17]  R17       1
    x_kimjn[0,2,8,1,17]  R36       1
    x_kimjn[0,2,8,1,17]  R40       1
    x_kimjn[0,2,8,1,17]  R125      172.5
    x_kimjn[0,2,8,1,17]  R197      -172.5
    x_kimjn[0,2,8,1,0]  R3        1
    x_kimjn[0,2,8,1,0]  R12       -1
    x_kimjn[0,2,8,1,0]  R18       1
    x_kimjn[0,2,8,1,0]  R40       1
    x_kimjn[0,2,8,1,0]  R126      172.5
    x_kimjn[0,2,8,1,0]  R198      -172.5
    x_kimjn[0,2,8,2,1]  OBJ       0
    x_kimjn[0,2,8,2,2]  OBJ       0
    x_kimjn[0,2,8,2,9]  OBJ       0
    x_kimjn[0,2,8,2,12]  OBJ       0
    x_kimjn[0,2,8,2,10]  OBJ       0
    x_kimjn[0,2,8,2,5]  OBJ       0
    x_kimjn[0,2,8,2,6]  OBJ       0
    x_kimjn[0,2,8,2,7]  OBJ       0
    x_kimjn[0,2,8,2,8]  OBJ       0
    x_kimjn[0,2,8,2,13]  OBJ       0
    x_kimjn[0,2,8,2,0]  OBJ       0
    x_kimjn[0,2,8,3,0]  R12       -1
    x_kimjn[0,2,8,3,0]  R15       -1
    x_kimjn[0,2,8,3,0]  R39       1
    x_kimjn[0,2,8,3,0]  R40       1
    x_kimjn[0,2,8,3,0]  R127      172.5
    x_kimjn[0,2,8,3,0]  R199      -172.5
    x_kimjn[0,2,8,4,0]  R12       -1
    x_kimjn[0,2,8,4,0]  R16       -1
    x_kimjn[0,2,8,4,0]  R40       2
    x_kimjn[0,2,8,4,0]  R128      172.5
    x_kimjn[0,2,8,4,0]  R200      -172.5
    x_kimjn[0,2,13,1,17]  R2        1
    x_kimjn[0,2,13,1,17]  R13       -1
    x_kimjn[0,2,13,1,17]  R17       1
    x_kimjn[0,2,13,1,17]  R36       1
    x_kimjn[0,2,13,1,17]  R40       1
    x_kimjn[0,2,13,1,17]  R129      172.5
    x_kimjn[0,2,13,1,17]  R201      -172.5
    x_kimjn[0,2,13,1,0]  R3        1
    x_kimjn[0,2,13,1,0]  R13       -1
    x_kimjn[0,2,13,1,0]  R18       1
    x_kimjn[0,2,13,1,0]  R40       1
    x_kimjn[0,2,13,1,0]  R130      172.5
    x_kimjn[0,2,13,1,0]  R202      -172.5
    x_kimjn[0,2,13,2,1]  OBJ       0
    x_kimjn[0,2,13,2,2]  OBJ       0
    x_kimjn[0,2,13,2,9]  OBJ       0
    x_kimjn[0,2,13,2,12]  OBJ       0
    x_kimjn[0,2,13,2,10]  OBJ       0
    x_kimjn[0,2,13,2,5]  OBJ       0
    x_kimjn[0,2,13,2,6]  OBJ       0
    x_kimjn[0,2,13,2,7]  OBJ       0
    x_kimjn[0,2,13,2,8]  OBJ       0
    x_kimjn[0,2,13,2,13]  OBJ       0
    x_kimjn[0,2,13,2,0]  OBJ       0
    x_kimjn[0,2,13,3,0]  R13       -1
    x_kimjn[0,2,13,3,0]  R15       -1
    x_kimjn[0,2,13,3,0]  R39       1
    x_kimjn[0,2,13,3,0]  R40       1
    x_kimjn[0,2,13,3,0]  R131      172.5
    x_kimjn[0,2,13,3,0]  R203      -172.5
    x_kimjn[0,2,13,4,0]  R13       -1
    x_kimjn[0,2,13,4,0]  R16       -1
    x_kimjn[0,2,13,4,0]  R40       2
    x_kimjn[0,2,13,4,0]  R132      172.5
    x_kimjn[0,2,13,4,0]  R204      -172.5
    x_kimjn[0,2,0,1,17]  R2        1
    x_kimjn[0,2,0,1,17]  R14       -1
    x_kimjn[0,2,0,1,17]  R17       1
    x_kimjn[0,2,0,1,17]  R36       1
    x_kimjn[0,2,0,1,17]  R133      172.5
    x_kimjn[0,2,0,1,17]  R205      -172.5
    x_kimjn[0,2,0,1,0]  R3        1
    x_kimjn[0,2,0,1,0]  R14       -1
    x_kimjn[0,2,0,1,0]  R18       1
    x_kimjn[0,2,0,1,0]  R134      172.5
    x_kimjn[0,2,0,1,0]  R206      -172.5
    x_kimjn[0,2,0,2,1]  OBJ       0
    x_kimjn[0,2,0,2,2]  OBJ       0
    x_kimjn[0,2,0,2,9]  OBJ       0
    x_kimjn[0,2,0,2,12]  OBJ       0
    x_kimjn[0,2,0,2,10]  OBJ       0
    x_kimjn[0,2,0,2,5]  OBJ       0
    x_kimjn[0,2,0,2,6]  OBJ       0
    x_kimjn[0,2,0,2,7]  OBJ       0
    x_kimjn[0,2,0,2,8]  OBJ       0
    x_kimjn[0,2,0,2,13]  OBJ       0
    x_kimjn[0,2,0,2,0]  OBJ       0
    x_kimjn[0,2,0,3,0]  R14       -1
    x_kimjn[0,2,0,3,0]  R15       -1
    x_kimjn[0,2,0,3,0]  R39       1
    x_kimjn[0,2,0,3,0]  R135      172.5
    x_kimjn[0,2,0,3,0]  R207      -172.5
    x_kimjn[0,2,0,4,0]  R14       -1
    x_kimjn[0,2,0,4,0]  R16       -1
    x_kimjn[0,2,0,4,0]  R40       1
    x_kimjn[0,2,0,4,0]  R136      172.5
    x_kimjn[0,2,0,4,0]  R208      -172.5
    x_kimjn[0,3,0,1,17]  OBJ       0
    x_kimjn[0,3,0,1,0]  OBJ       0
    x_kimjn[0,3,0,2,1]  OBJ       0
    x_kimjn[0,3,0,2,2]  OBJ       0
    x_kimjn[0,3,0,2,9]  OBJ       0
    x_kimjn[0,3,0,2,12]  OBJ       0
    x_kimjn[0,3,0,2,10]  OBJ       0
    x_kimjn[0,3,0,2,5]  OBJ       0
    x_kimjn[0,3,0,2,6]  OBJ       0
    x_kimjn[0,3,0,2,7]  OBJ       0
    x_kimjn[0,3,0,2,8]  OBJ       0
    x_kimjn[0,3,0,2,13]  OBJ       0
    x_kimjn[0,3,0,2,0]  OBJ       0
    x_kimjn[0,3,0,3,0]  OBJ       0
    x_kimjn[0,3,0,4,0]  R15       1
    x_kimjn[0,3,0,4,0]  R16       -1
    x_kimjn[0,3,0,4,0]  R30       1
    x_kimjn[0,3,0,4,0]  R40       1
    x_kimjn[0,3,0,4,0]  R137      172.5
    x_kimjn[0,3,0,4,0]  R209      -172.5
    x_kimjn[0,4,0,1,17]  OBJ       0
    x_kimjn[0,4,0,1,0]  OBJ       0
    x_kimjn[0,4,0,2,1]  OBJ       0
    x_kimjn[0,4,0,2,2]  OBJ       0
    x_kimjn[0,4,0,2,9]  OBJ       0
    x_kimjn[0,4,0,2,12]  OBJ       0
    x_kimjn[0,4,0,2,10]  OBJ       0
    x_kimjn[0,4,0,2,5]  OBJ       0
    x_kimjn[0,4,0,2,6]  OBJ       0
    x_kimjn[0,4,0,2,7]  OBJ       0
    x_kimjn[0,4,0,2,8]  OBJ       0
    x_kimjn[0,4,0,2,13]  OBJ       0
    x_kimjn[0,4,0,2,0]  OBJ       0
    x_kimjn[0,4,0,3,0]  R15       -1
    x_kimjn[0,4,0,3,0]  R16       1
    x_kimjn[0,4,0,3,0]  R31       1
    x_kimjn[0,4,0,3,0]  R39       1
    x_kimjn[0,4,0,3,0]  R138      172.5
    x_kimjn[0,4,0,3,0]  R210      -172.5
    x_kimjn[0,4,0,4,0]  OBJ       0
    xs_kim[0,1,17]  R0        1
    xs_kim[0,1,17]  R2        1
    xs_kim[0,1,17]  R17       1
    xs_kim[0,1,17]  R36       1
    xs_kim[0,1,17]  R211      172.5
    xs_kim[0,1,17]  R224      -172.5
    xs_kim[0,1,0]  R0        1
    xs_kim[0,1,0]  R3        1
    xs_kim[0,1,0]  R18       1
    xs_kim[0,1,0]  R212      172.5
    xs_kim[0,1,0]  R225      -172.5
    xs_kim[0,2,1]  R0        1
    xs_kim[0,2,1]  R4        1
    xs_kim[0,2,1]  R19       1
    xs_kim[0,2,1]  R37       1
    xs_kim[0,2,1]  R213      172.5
    xs_kim[0,2,1]  R226      -172.5
    xs_kim[0,2,2]  R0        1
    xs_kim[0,2,2]  R5        1
    xs_kim[0,2,2]  R20       1
    xs_kim[0,2,2]  R37       1
    xs_kim[0,2,2]  R214      172.5
    xs_kim[0,2,2]  R227      -172.5
    xs_kim[0,2,9]  R0        1
    xs_kim[0,2,9]  R6        1
    xs_kim[0,2,9]  R21       1
    xs_kim[0,2,9]  R37       1
    xs_kim[0,2,9]  R215      172.5
    xs_kim[0,2,9]  R228      -172.5
    xs_kim[0,2,12]  R0        1
    xs_kim[0,2,12]  R7        1
    xs_kim[0,2,12]  R22       1
    xs_kim[0,2,12]  R37       1
    xs_kim[0,2,12]  R216      172.5
    xs_kim[0,2,12]  R229      -172.5
    xs_kim[0,2,10]  R0        1
    xs_kim[0,2,10]  R8        1
    xs_kim[0,2,10]  R23       1
    xs_kim[0,2,10]  R37       1
    xs_kim[0,2,10]  R217      172.5
    xs_kim[0,2,10]  R230      -172.5
    xs_kim[0,2,5]  R0        1
    xs_kim[0,2,5]  R9        1
    xs_kim[0,2,5]  R24       1
    xs_kim[0,2,5]  R37       1
    xs_kim[0,2,5]  R218      172.5
    xs_kim[0,2,5]  R231      -172.5
    xs_kim[0,2,6]  R0        1
    xs_kim[0,2,6]  R10       1
    xs_kim[0,2,6]  R25       1
    xs_kim[0,2,6]  R37       1
    xs_kim[0,2,6]  R219      172.5
    xs_kim[0,2,6]  R232      -172.5
    xs_kim[0,2,7]  R0        1
    xs_kim[0,2,7]  R11       1
    xs_kim[0,2,7]  R26       1
    xs_kim[0,2,7]  R37       1
    xs_kim[0,2,7]  R220      172.5
    xs_kim[0,2,7]  R233      -172.5
    xs_kim[0,2,8]  R0        1
    xs_kim[0,2,8]  R12       1
    xs_kim[0,2,8]  R27       1
    xs_kim[0,2,8]  R37       1
    xs_kim[0,2,8]  R221      172.5
    xs_kim[0,2,8]  R234      -172.5
    xs_kim[0,2,13]  R0        1
    xs_kim[0,2,13]  R13       1
    xs_kim[0,2,13]  R28       1
    xs_kim[0,2,13]  R37       1
    xs_kim[0,2,13]  R222      172.5
    xs_kim[0,2,13]  R235      -172.5
    xs_kim[0,2,0]  R0        1
    xs_kim[0,2,0]  R14       1
    xs_kim[0,2,0]  R29       1
    xs_kim[0,2,0]  R223      172.5
    xs_kim[0,2,0]  R236      -172.5
    xe_kjn[0,3,0]  R1        1
    xe_kjn[0,3,0]  R15       1
    xe_kjn[0,3,0]  R30       1
    xe_kjn[0,3,0]  R237      172.5
    xe_kjn[0,3,0]  R239      -172.5
    xe_kjn[0,4,0]  R1        1
    xe_kjn[0,4,0]  R16       1
    xe_kjn[0,4,0]  R31       1
    xe_kjn[0,4,0]  R238      172.5
    xe_kjn[0,4,0]  R240      -172.5
    xod_k[0]  R0        1
    xod_k[0]  R1        1
    xod_k[0]  R38       1
    y_kim[0,1,17]  R17       -1
    y_kim[0,1,17]  R32       1
    y_kim[0,1,17]  R250      7
    y_kim[0,1,0]  R18       -1
    y_kim[0,1,0]  R32       2
    y_kim[0,2,1]  R19       -1
    y_kim[0,2,1]  R33       1
    y_kim[0,2,1]  R251      8
    y_kim[0,2,2]  R20       -1
    y_kim[0,2,2]  R33       1
    y_kim[0,2,2]  R252      5
    y_kim[0,2,9]  R21       -1
    y_kim[0,2,9]  R33       1
    y_kim[0,2,9]  R253      4
    y_kim[0,2,12]  R22       -1
    y_kim[0,2,12]  R33       1
    y_kim[0,2,12]  R254      4
    y_kim[0,2,10]  R23       -1
    y_kim[0,2,10]  R33       1
    y_kim[0,2,10]  R255      9
    y_kim[0,2,5]  R24       -1
    y_kim[0,2,5]  R33       1
    y_kim[0,2,5]  R256      8
    y_kim[0,2,6]  R25       -1
    y_kim[0,2,6]  R33       1
    y_kim[0,2,6]  R257      7
    y_kim[0,2,7]  R26       -1
    y_kim[0,2,7]  R33       1
    y_kim[0,2,7]  R258      7
    y_kim[0,2,8]  R27       -1
    y_kim[0,2,8]  R33       1
    y_kim[0,2,8]  R259      10
    y_kim[0,2,13]  R28       -1
    y_kim[0,2,13]  R33       1
    y_kim[0,2,13]  R260      7
    y_kim[0,2,0]  R29       -1
    y_kim[0,2,0]  R33       2
    y_kim[0,3,0]  R30       -1
    y_kim[0,3,0]  R34       2
    y_kim[0,3,0]  R261      -0.1
    y_kim[0,4,0]  R31       -1
    y_kim[0,4,0]  R35       2
    y_kim[0,4,0]  R262      -0.1
    z_ki[0,1]  OBJ       1
    z_ki[0,1]  R36       -1
    z_ki[0,1]  R263      1
    z_ki[0,2]  OBJ       1
    z_ki[0,2]  R37       -1
    z_ki[0,2]  R263      1
    MARKER    'MARKER'                 'INTEND'
    t_ki[0,0,0]  R211      1
    t_ki[0,0,0]  R212      1
    t_ki[0,0,0]  R213      1
    t_ki[0,0,0]  R214      1
    t_ki[0,0,0]  R215      1
    t_ki[0,0,0]  R216      1
    t_ki[0,0,0]  R217      1
    t_ki[0,0,0]  R218      1
    t_ki[0,0,0]  R219      1
    t_ki[0,0,0]  R220      1
    t_ki[0,0,0]  R221      1
    t_ki[0,0,0]  R222      1
    t_ki[0,0,0]  R223      1
    t_ki[0,0,0]  R224      1
    t_ki[0,0,0]  R225      1
    t_ki[0,0,0]  R226      1
    t_ki[0,0,0]  R227      1
    t_ki[0,0,0]  R228      1
    t_ki[0,0,0]  R229      1
    t_ki[0,0,0]  R230      1
    t_ki[0,0,0]  R231      1
    t_ki[0,0,0]  R232      1
    t_ki[0,0,0]  R233      1
    t_ki[0,0,0]  R234      1
    t_ki[0,0,0]  R235      1
    t_ki[0,0,0]  R236      1
    t_ki[0,0,0]  R249      -1
    t_ki[0,1,17]  R41       1
    t_ki[0,1,17]  R42       1
    t_ki[0,1,17]  R67       1
    t_ki[0,1,17]  R68       1
    t_ki[0,1,17]  R69       1
    t_ki[0,1,17]  R70       1
    t_ki[0,1,17]  R71       1
    t_ki[0,1,17]  R72       1
    t_ki[0,1,17]  R73       1
    t_ki[0,1,17]  R74       1
    t_ki[0,1,17]  R75       1
    t_ki[0,1,17]  R76       1
    t_ki[0,1,17]  R77       1
    t_ki[0,1,17]  R78       1
    t_ki[0,1,17]  R79       1
    t_ki[0,1,17]  R93       -1
    t_ki[0,1,17]  R97       -1
    t_ki[0,1,17]  R101      -1
    t_ki[0,1,17]  R105      -1
    t_ki[0,1,17]  R109      -1
    t_ki[0,1,17]  R113      -1
    t_ki[0,1,17]  R117      -1
    t_ki[0,1,17]  R121      -1
    t_ki[0,1,17]  R125      -1
    t_ki[0,1,17]  R129      -1
    t_ki[0,1,17]  R133      -1
    t_ki[0,1,17]  R139      1
    t_ki[0,1,17]  R140      1
    t_ki[0,1,17]  R141      1
    t_ki[0,1,17]  R142      1
    t_ki[0,1,17]  R143      1
    t_ki[0,1,17]  R144      1
    t_ki[0,1,17]  R145      1
    t_ki[0,1,17]  R146      1
    t_ki[0,1,17]  R147      1
    t_ki[0,1,17]  R148      1
    t_ki[0,1,17]  R149      1
    t_ki[0,1,17]  R150      1
    t_ki[0,1,17]  R151      1
    t_ki[0,1,17]  R165      -1
    t_ki[0,1,17]  R169      -1
    t_ki[0,1,17]  R173      -1
    t_ki[0,1,17]  R177      -1
    t_ki[0,1,17]  R181      -1
    t_ki[0,1,17]  R185      -1
    t_ki[0,1,17]  R189      -1
    t_ki[0,1,17]  R193      -1
    t_ki[0,1,17]  R197      -1
    t_ki[0,1,17]  R201      -1
    t_ki[0,1,17]  R205      -1
    t_ki[0,1,17]  R211      -1
    t_ki[0,1,17]  R224      -1
    t_ki[0,1,17]  R250      -1
    t_ki[0,1,0]  R43       1
    t_ki[0,1,0]  R44       1
    t_ki[0,1,0]  R80       1
    t_ki[0,1,0]  R81       1
    t_ki[0,1,0]  R82       1
    t_ki[0,1,0]  R83       1
    t_ki[0,1,0]  R84       1
    t_ki[0,1,0]  R85       1
    t_ki[0,1,0]  R86       1
    t_ki[0,1,0]  R87       1
    t_ki[0,1,0]  R88       1
    t_ki[0,1,0]  R89       1
    t_ki[0,1,0]  R90       1
    t_ki[0,1,0]  R91       1
    t_ki[0,1,0]  R92       1
    t_ki[0,1,0]  R94       -1
    t_ki[0,1,0]  R98       -1
    t_ki[0,1,0]  R102      -1
    t_ki[0,1,0]  R106      -1
    t_ki[0,1,0]  R110      -1
    t_ki[0,1,0]  R114      -1
    t_ki[0,1,0]  R118      -1
    t_ki[0,1,0]  R122      -1
    t_ki[0,1,0]  R126      -1
    t_ki[0,1,0]  R130      -1
    t_ki[0,1,0]  R134      -1
    t_ki[0,1,0]  R152      1
    t_ki[0,1,0]  R153      1
    t_ki[0,1,0]  R154      1
    t_ki[0,1,0]  R155      1
    t_ki[0,1,0]  R156      1
    t_ki[0,1,0]  R157      1
    t_ki[0,1,0]  R158      1
    t_ki[0,1,0]  R159      1
    t_ki[0,1,0]  R160      1
    t_ki[0,1,0]  R161      1
    t_ki[0,1,0]  R162      1
    t_ki[0,1,0]  R163      1
    t_ki[0,1,0]  R164      1
    t_ki[0,1,0]  R166      -1
    t_ki[0,1,0]  R170      -1
    t_ki[0,1,0]  R174      -1
    t_ki[0,1,0]  R178      -1
    t_ki[0,1,0]  R182      -1
    t_ki[0,1,0]  R186      -1
    t_ki[0,1,0]  R190      -1
    t_ki[0,1,0]  R194      -1
    t_ki[0,1,0]  R198      -1
    t_ki[0,1,0]  R202      -1
    t_ki[0,1,0]  R206      -1
    t_ki[0,1,0]  R212      -1
    t_ki[0,1,0]  R225      -1
    t_ki[0,1,0]  R247      -1
    t_ki[0,1,0]  R250      1
    t_ki[0,2,1]  R45       1
    t_ki[0,2,1]  R46       1
    t_ki[0,2,1]  R67       -1
    t_ki[0,2,1]  R80       -1
    t_ki[0,2,1]  R93       1
    t_ki[0,2,1]  R94       1
    t_ki[0,2,1]  R95       1
    t_ki[0,2,1]  R96       1
    t_ki[0,2,1]  R139      -1
    t_ki[0,2,1]  R152      -1
    t_ki[0,2,1]  R165      1
    t_ki[0,2,1]  R166      1
    t_ki[0,2,1]  R167      1
    t_ki[0,2,1]  R168      1
    t_ki[0,2,1]  R213      -1
    t_ki[0,2,1]  R226      -1
    t_ki[0,2,1]  R251      -1
    t_ki[0,2,2]  R47       1
    t_ki[0,2,2]  R48       1
    t_ki[0,2,2]  R68       -1
    t_ki[0,2,2]  R81       -1
    t_ki[0,2,2]  R97       1
    t_ki[0,2,2]  R98       1
    t_ki[0,2,2]  R99       1
    t_ki[0,2,2]  R100      1
    t_ki[0,2,2]  R140      -1
    t_ki[0,2,2]  R153      -1
    t_ki[0,2,2]  R169      1
    t_ki[0,2,2]  R170      1
    t_ki[0,2,2]  R171      1
    t_ki[0,2,2]  R172      1
    t_ki[0,2,2]  R214      -1
    t_ki[0,2,2]  R227      -1
    t_ki[0,2,2]  R252      -1
    t_ki[0,2,9]  R49       1
    t_ki[0,2,9]  R50       1
    t_ki[0,2,9]  R69       -1
    t_ki[0,2,9]  R82       -1
    t_ki[0,2,9]  R101      1
    t_ki[0,2,9]  R102      1
    t_ki[0,2,9]  R103      1
    t_ki[0,2,9]  R104      1
    t_ki[0,2,9]  R141      -1
    t_ki[0,2,9]  R154      -1
    t_ki[0,2,9]  R173      1
    t_ki[0,2,9]  R174      1
    t_ki[0,2,9]  R175      1
    t_ki[0,2,9]  R176      1
    t_ki[0,2,9]  R215      -1
    t_ki[0,2,9]  R228      -1
    t_ki[0,2,9]  R253      -1
    t_ki[0,2,12]  R51       1
    t_ki[0,2,12]  R52       1
    t_ki[0,2,12]  R70       -1
    t_ki[0,2,12]  R83       -1
    t_ki[0,2,12]  R105      1
    t_ki[0,2,12]  R106      1
    t_ki[0,2,12]  R107      1
    t_ki[0,2,12]  R108      1
    t_ki[0,2,12]  R142      -1
    t_ki[0,2,12]  R155      -1
    t_ki[0,2,12]  R177      1
    t_ki[0,2,12]  R178      1
    t_ki[0,2,12]  R179      1
    t_ki[0,2,12]  R180      1
    t_ki[0,2,12]  R216      -1
    t_ki[0,2,12]  R229      -1
    t_ki[0,2,12]  R254      -1
    t_ki[0,2,10]  R53       1
    t_ki[0,2,10]  R54       1
    t_ki[0,2,10]  R71       -1
    t_ki[0,2,10]  R84       -1
    t_ki[0,2,10]  R109      1
    t_ki[0,2,10]  R110      1
    t_ki[0,2,10]  R111      1
    t_ki[0,2,10]  R112      1
    t_ki[0,2,10]  R143      -1
    t_ki[0,2,10]  R156      -1
    t_ki[0,2,10]  R181      1
    t_ki[0,2,10]  R182      1
    t_ki[0,2,10]  R183      1
    t_ki[0,2,10]  R184      1
    t_ki[0,2,10]  R217      -1
    t_ki[0,2,10]  R230      -1
    t_ki[0,2,10]  R255      -1
    t_ki[0,2,5]  R55       1
    t_ki[0,2,5]  R56       1
    t_ki[0,2,5]  R72       -1
    t_ki[0,2,5]  R85       -1
    t_ki[0,2,5]  R113      1
    t_ki[0,2,5]  R114      1
    t_ki[0,2,5]  R115      1
    t_ki[0,2,5]  R116      1
    t_ki[0,2,5]  R144      -1
    t_ki[0,2,5]  R157      -1
    t_ki[0,2,5]  R185      1
    t_ki[0,2,5]  R186      1
    t_ki[0,2,5]  R187      1
    t_ki[0,2,5]  R188      1
    t_ki[0,2,5]  R218      -1
    t_ki[0,2,5]  R231      -1
    t_ki[0,2,5]  R256      -1
    t_ki[0,2,6]  R57       1
    t_ki[0,2,6]  R58       1
    t_ki[0,2,6]  R73       -1
    t_ki[0,2,6]  R86       -1
    t_ki[0,2,6]  R117      1
    t_ki[0,2,6]  R118      1
    t_ki[0,2,6]  R119      1
    t_ki[0,2,6]  R120      1
    t_ki[0,2,6]  R145      -1
    t_ki[0,2,6]  R158      -1
    t_ki[0,2,6]  R189      1
    t_ki[0,2,6]  R190      1
    t_ki[0,2,6]  R191      1
    t_ki[0,2,6]  R192      1
    t_ki[0,2,6]  R219      -1
    t_ki[0,2,6]  R232      -1
    t_ki[0,2,6]  R257      -1
    t_ki[0,2,7]  R59       1
    t_ki[0,2,7]  R60       1
    t_ki[0,2,7]  R74       -1
    t_ki[0,2,7]  R87       -1
    t_ki[0,2,7]  R121      1
    t_ki[0,2,7]  R122      1
    t_ki[0,2,7]  R123      1
    t_ki[0,2,7]  R124      1
    t_ki[0,2,7]  R146      -1
    t_ki[0,2,7]  R159      -1
    t_ki[0,2,7]  R193      1
    t_ki[0,2,7]  R194      1
    t_ki[0,2,7]  R195      1
    t_ki[0,2,7]  R196      1
    t_ki[0,2,7]  R220      -1
    t_ki[0,2,7]  R233      -1
    t_ki[0,2,7]  R258      -1
    t_ki[0,2,8]  R61       1
    t_ki[0,2,8]  R62       1
    t_ki[0,2,8]  R75       -1
    t_ki[0,2,8]  R88       -1
    t_ki[0,2,8]  R125      1
    t_ki[0,2,8]  R126      1
    t_ki[0,2,8]  R127      1
    t_ki[0,2,8]  R128      1
    t_ki[0,2,8]  R147      -1
    t_ki[0,2,8]  R160      -1
    t_ki[0,2,8]  R197      1
    t_ki[0,2,8]  R198      1
    t_ki[0,2,8]  R199      1
    t_ki[0,2,8]  R200      1
    t_ki[0,2,8]  R221      -1
    t_ki[0,2,8]  R234      -1
    t_ki[0,2,8]  R259      -1
    t_ki[0,2,13]  R63       1
    t_ki[0,2,13]  R64       1
    t_ki[0,2,13]  R76       -1
    t_ki[0,2,13]  R89       -1
    t_ki[0,2,13]  R129      1
    t_ki[0,2,13]  R130      1
    t_ki[0,2,13]  R131      1
    t_ki[0,2,13]  R132      1
    t_ki[0,2,13]  R148      -1
    t_ki[0,2,13]  R161      -1
    t_ki[0,2,13]  R201      1
    t_ki[0,2,13]  R202      1
    t_ki[0,2,13]  R203      1
    t_ki[0,2,13]  R204      1
    t_ki[0,2,13]  R222      -1
    t_ki[0,2,13]  R235      -1
    t_ki[0,2,13]  R260      -1
    t_ki[0,2,0]  R65       1
    t_ki[0,2,0]  R66       1
    t_ki[0,2,0]  R77       -1
    t_ki[0,2,0]  R90       -1
    t_ki[0,2,0]  R133      1
    t_ki[0,2,0]  R134      1
    t_ki[0,2,0]  R135      1
    t_ki[0,2,0]  R136      1
    t_ki[0,2,0]  R149      -1
    t_ki[0,2,0]  R162      -1
    t_ki[0,2,0]  R205      1
    t_ki[0,2,0]  R206      1
    t_ki[0,2,0]  R207      1
    t_ki[0,2,0]  R208      1
    t_ki[0,2,0]  R223      -1
    t_ki[0,2,0]  R236      -1
    t_ki[0,2,0]  R248      -1
    t_ki[0,2,0]  R251      1
    t_ki[0,2,0]  R252      1
    t_ki[0,2,0]  R253      1
    t_ki[0,2,0]  R254      1
    t_ki[0,2,0]  R255      1
    t_ki[0,2,0]  R256      1
    t_ki[0,2,0]  R257      1
    t_ki[0,2,0]  R258      1
    t_ki[0,2,0]  R259      1
    t_ki[0,2,0]  R260      1
    t_ki[0,3,0]  R41       -1
    t_ki[0,3,0]  R42       -1
    t_ki[0,3,0]  R43       -1
    t_ki[0,3,0]  R44       -1
    t_ki[0,3,0]  R78       -1
    t_ki[0,3,0]  R91       -1
    t_ki[0,3,0]  R95       -1
    t_ki[0,3,0]  R99       -1
    t_ki[0,3,0]  R103      -1
    t_ki[0,3,0]  R107      -1
    t_ki[0,3,0]  R111      -1
    t_ki[0,3,0]  R115      -1
    t_ki[0,3,0]  R119      -1
    t_ki[0,3,0]  R123      -1
    t_ki[0,3,0]  R127      -1
    t_ki[0,3,0]  R131      -1
    t_ki[0,3,0]  R135      -1
    t_ki[0,3,0]  R137      1
    t_ki[0,3,0]  R138      -1
    t_ki[0,3,0]  R150      -1
    t_ki[0,3,0]  R163      -1
    t_ki[0,3,0]  R167      -1
    t_ki[0,3,0]  R171      -1
    t_ki[0,3,0]  R175      -1
    t_ki[0,3,0]  R179      -1
    t_ki[0,3,0]  R183      -1
    t_ki[0,3,0]  R187      -1
    t_ki[0,3,0]  R191      -1
    t_ki[0,3,0]  R195      -1
    t_ki[0,3,0]  R199      -1
    t_ki[0,3,0]  R203      -1
    t_ki[0,3,0]  R207      -1
    t_ki[0,3,0]  R209      1
    t_ki[0,3,0]  R210      -1
    t_ki[0,3,0]  R237      1
    t_ki[0,3,0]  R239      1
    t_ki[0,3,0]  R241      1
    t_ki[0,3,0]  R243      1
    t_ki[0,3,0]  R247      1
    t_ki[0,4,0]  R45       -1
    t_ki[0,4,0]  R46       -1
    t_ki[0,4,0]  R47       -1
    t_ki[0,4,0]  R48       -1
    t_ki[0,4,0]  R49       -1
    t_ki[0,4,0]  R50       -1
    t_ki[0,4,0]  R51       -1
    t_ki[0,4,0]  R52       -1
    t_ki[0,4,0]  R53       -1
    t_ki[0,4,0]  R54       -1
    t_ki[0,4,0]  R55       -1
    t_ki[0,4,0]  R56       -1
    t_ki[0,4,0]  R57       -1
    t_ki[0,4,0]  R58       -1
    t_ki[0,4,0]  R59       -1
    t_ki[0,4,0]  R60       -1
    t_ki[0,4,0]  R61       -1
    t_ki[0,4,0]  R62       -1
    t_ki[0,4,0]  R63       -1
    t_ki[0,4,0]  R64       -1
    t_ki[0,4,0]  R65       -1
    t_ki[0,4,0]  R66       -1
    t_ki[0,4,0]  R79       -1
    t_ki[0,4,0]  R92       -1
    t_ki[0,4,0]  R96       -1
    t_ki[0,4,0]  R100      -1
    t_ki[0,4,0]  R104      -1
    t_ki[0,4,0]  R108      -1
    t_ki[0,4,0]  R112      -1
    t_ki[0,4,0]  R116      -1
    t_ki[0,4,0]  R120      -1
    t_ki[0,4,0]  R124      -1
    t_ki[0,4,0]  R128      -1
    t_ki[0,4,0]  R132      -1
    t_ki[0,4,0]  R136      -1
    t_ki[0,4,0]  R137      -1
    t_ki[0,4,0]  R138      1
    t_ki[0,4,0]  R151      -1
    t_ki[0,4,0]  R164      -1
    t_ki[0,4,0]  R168      -1
    t_ki[0,4,0]  R172      -1
    t_ki[0,4,0]  R176      -1
    t_ki[0,4,0]  R180      -1
    t_ki[0,4,0]  R184      -1
    t_ki[0,4,0]  R188      -1
    t_ki[0,4,0]  R192      -1
    t_ki[0,4,0]  R196      -1
    t_ki[0,4,0]  R200      -1
    t_ki[0,4,0]  R204      -1
    t_ki[0,4,0]  R208      -1
    t_ki[0,4,0]  R209      -1
    t_ki[0,4,0]  R210      1
    t_ki[0,4,0]  R238      1
    t_ki[0,4,0]  R240      1
    t_ki[0,4,0]  R242      1
    t_ki[0,4,0]  R244      1
    t_ki[0,4,0]  R248      1
    t_ki[0,5,0]  R237      -1
    t_ki[0,5,0]  R238      -1
    t_ki[0,5,0]  R239      -1
    t_ki[0,5,0]  R240      -1
    t_ki[0,5,0]  R245      1
    t_ki[0,5,0]  R246      1
    t_ki[0,5,0]  R249      1
RHS
    RHS1      R0        1
    RHS1      R1        1
    RHS1      R32       1
    RHS1      R33       1
    RHS1      R34       1
    RHS1      R35       1
    RHS1      R41       -44
    RHS1      R42       -44
    RHS1      R43       -50
    RHS1      R44       -50
    RHS1      R45       -27
    RHS1      R46       -27
    RHS1      R47       -25
    RHS1      R48       -25
    RHS1      R49       -22
    RHS1      R50       -22
    RHS1      R51       -18
    RHS1      R52       -18
    RHS1      R53       -29
    RHS1      R54       -29
    RHS1      R55       -26
    RHS1      R56       -26
    RHS1      R57       -23
    RHS1      R58       -23
    RHS1      R59       -22
    RHS1      R60       -22
    RHS1      R61       -26
    RHS1      R62       -26
    RHS1      R63       -21
    RHS1      R64       -21
    RHS1      R65       -22
    RHS1      R66       -22
    RHS1      R67       155.5
    RHS1      R68       150.5
    RHS1      R69       147.5
    RHS1      R70       146.5
    RHS1      R71       157.5
    RHS1      R72       143.5
    RHS1      R73       143.5
    RHS1      R74       143.5
    RHS1      R75       141.5
    RHS1      R76       143.5
    RHS1      R77       148.5
    RHS1      R78       128.5
    RHS1      R79       128.5
    RHS1      R80       149.5
    RHS1      R81       144.5
    RHS1      R82       140.5
    RHS1      R83       140.5
    RHS1      R84       150.5
    RHS1      R85       136.5
    RHS1      R86       137.5
    RHS1      R87       137.5
    RHS1      R88       134.5
    RHS1      R89       137.5
    RHS1      R90       142.5
    RHS1      R91       122.5
    RHS1      R92       122.5
    RHS1      R93       155.5
    RHS1      R94       150.5
    RHS1      R95       145.5
    RHS1      R96       145.5
    RHS1      R97       150.5
    RHS1      R98       145.5
    RHS1      R99       147.5
    RHS1      R100      147.5
    RHS1      R101      147.5
    RHS1      R102      142.5
    RHS1      R103      150.5
    RHS1      R104      150.5
    RHS1      R105      146.5
    RHS1      R106      141.5
    RHS1      R107      154.5
    RHS1      R108      154.5
    RHS1      R109      157.5
    RHS1      R110      151.5
    RHS1      R111      143.5
    RHS1      R112      143.5
    RHS1      R113      144.5
    RHS1      R114      138.5
    RHS1      R115      146.5
    RHS1      R116      146.5
    RHS1      R117      143.5
    RHS1      R118      138.5
    RHS1      R119      149.5
    RHS1      R120      149.5
    RHS1      R121      143.5
    RHS1      R122      138.5
    RHS1      R123      150.5
    RHS1      R124      150.5
    RHS1      R125      140.5
    RHS1      R126      135.5
    RHS1      R127      146.5
    RHS1      R128      146.5
    RHS1      R129      143.5
    RHS1      R130      138.5
    RHS1      R131      151.5
    RHS1      R132      151.5
    RHS1      R133      148.5
    RHS1      R134      143.5
    RHS1      R135      150.5
    RHS1      R136      150.5
    RHS1      R137      172.4
    RHS1      R138      172.4
    RHS1      R139      -189.5
    RHS1      R140      -194.5
    RHS1      R141      -197.5
    RHS1      R142      -198.5
    RHS1      R143      -187.5
    RHS1      R144      -201.5
    RHS1      R145      -201.5
    RHS1      R146      -201.5
    RHS1      R147      -203.5
    RHS1      R148      -201.5
    RHS1      R149      -196.5
    RHS1      R150      -216.5
    RHS1      R151      -216.5
    RHS1      R152      -195.5
    RHS1      R153      -200.5
    RHS1      R154      -204.5
    RHS1      R155      -204.5
    RHS1      R156      -194.5
    RHS1      R157      -208.5
    RHS1      R158      -207.5
    RHS1      R159      -207.5
    RHS1      R160      -210.5
    RHS1      R161      -207.5
    RHS1      R162      -202.5
    RHS1      R163      -222.5
    RHS1      R164      -222.5
    RHS1      R165      -189.5
    RHS1      R166      -194.5
    RHS1      R167      -199.5
    RHS1      R168      -199.5
    RHS1      R169      -194.5
    RHS1      R170      -199.5
    RHS1      R171      -197.5
    RHS1      R172      -197.5
    RHS1      R173      -197.5
    RHS1      R174      -202.5
    RHS1      R175      -194.5
    RHS1      R176      -194.5
    RHS1      R177      -198.5
    RHS1      R178      -203.5
    RHS1      R179      -190.5
    RHS1      R180      -190.5
    RHS1      R181      -187.5
    RHS1      R182      -193.5
    RHS1      R183      -201.5
    RHS1      R184      -201.5
    RHS1      R185      -200.5
    RHS1      R186      -206.5
    RHS1      R187      -198.5
    RHS1      R188      -198.5
    RHS1      R189      -201.5
    RHS1      R190      -206.5
    RHS1      R191      -195.5
    RHS1      R192      -195.5
    RHS1      R193      -201.5
    RHS1      R194      -206.5
    RHS1      R195      -194.5
    RHS1      R196      -194.5
    RHS1      R197      -204.5
    RHS1      R198      -209.5
    RHS1      R199      -198.5
    RHS1      R200      -198.5
    RHS1      R201      -201.5
    RHS1      R202      -206.5
    RHS1      R203      -193.5
    RHS1      R204      -193.5
    RHS1      R205      -196.5
    RHS1      R206      -201.5
    RHS1      R207      -194.5
    RHS1      R208      -194.5
    RHS1      R209      -172.6
    RHS1      R210      -172.6
    RHS1      R211      148.5
    RHS1      R212      143.5
    RHS1      R213      164.5
    RHS1      R214      167.5
    RHS1      R215      168.5
    RHS1      R216      168.5
    RHS1      R217      163.5
    RHS1      R218      164.5
    RHS1      R219      165.5
    RHS1      R220      165.5
    RHS1      R221      162.5
    RHS1      R222      165.5
    RHS1      R223      172.4
    RHS1      R224      -196.5
    RHS1      R225      -201.5
    RHS1      R226      -180.5
    RHS1      R227      -177.5
    RHS1      R228      -176.5
    RHS1      R229      -176.5
    RHS1      R230      -181.5
    RHS1      R231      -180.5
    RHS1      R232      -179.5
    RHS1      R233      -179.5
    RHS1      R234      -182.5
    RHS1      R235      -179.5
    RHS1      R236      -172.6
    RHS1      R237      172.4
    RHS1      R238      172.4
    RHS1      R239      -172.6
    RHS1      R240      -172.6
    RHS1      R241      119.9
    RHS1      R242      119.9
    RHS1      R243      149.9
    RHS1      R244      149.9
    RHS1      R245      120
    RHS1      R246      150
    RHS1      R247      1.3173333333333332e+02
    RHS1      R248      5.8266666666666659e+01
    RHS1      R249      69
    RHS1      R263      4
BOUNDS
 BV BND1      x_kimjn[0,1,17,1,17]
 BV BND1      x_kimjn[0,1,17,1,0]
 BV BND1      x_kimjn[0,1,17,2,1]
 BV BND1      x_kimjn[0,1,17,2,2]
 BV BND1      x_kimjn[0,1,17,2,9]
 BV BND1      x_kimjn[0,1,17,2,12]
 BV BND1      x_kimjn[0,1,17,2,10]
 BV BND1      x_kimjn[0,1,17,2,5]
 BV BND1      x_kimjn[0,1,17,2,6]
 BV BND1      x_kimjn[0,1,17,2,7]
 BV BND1      x_kimjn[0,1,17,2,8]
 BV BND1      x_kimjn[0,1,17,2,13]
 BV BND1      x_kimjn[0,1,17,2,0]
 BV BND1      x_kimjn[0,1,17,3,0]
 BV BND1      x_kimjn[0,1,17,4,0]
 BV BND1      x_kimjn[0,1,0,1,17]
 BV BND1      x_kimjn[0,1,0,1,0]
 BV BND1      x_kimjn[0,1,0,2,1]
 BV BND1      x_kimjn[0,1,0,2,2]
 BV BND1      x_kimjn[0,1,0,2,9]
 BV BND1      x_kimjn[0,1,0,2,12]
 BV BND1      x_kimjn[0,1,0,2,10]
 BV BND1      x_kimjn[0,1,0,2,5]
 BV BND1      x_kimjn[0,1,0,2,6]
 BV BND1      x_kimjn[0,1,0,2,7]
 BV BND1      x_kimjn[0,1,0,2,8]
 BV BND1      x_kimjn[0,1,0,2,13]
 BV BND1      x_kimjn[0,1,0,2,0]
 BV BND1      x_kimjn[0,1,0,3,0]
 BV BND1      x_kimjn[0,1,0,4,0]
 BV BND1      x_kimjn[0,2,1,1,17]
 BV BND1      x_kimjn[0,2,1,1,0]
 BV BND1      x_kimjn[0,2,1,2,1]
 BV BND1      x_kimjn[0,2,1,2,2]
 BV BND1      x_kimjn[0,2,1,2,9]
 BV BND1      x_kimjn[0,2,1,2,12]
 BV BND1      x_kimjn[0,2,1,2,10]
 BV BND1      x_kimjn[0,2,1,2,5]
 BV BND1      x_kimjn[0,2,1,2,6]
 BV BND1      x_kimjn[0,2,1,2,7]
 BV BND1      x_kimjn[0,2,1,2,8]
 BV BND1      x_kimjn[0,2,1,2,13]
 BV BND1      x_kimjn[0,2,1,2,0]
 BV BND1      x_kimjn[0,2,1,3,0]
 BV BND1      x_kimjn[0,2,1,4,0]
 BV BND1      x_kimjn[0,2,2,1,17]
 BV BND1      x_kimjn[0,2,2,1,0]
 BV BND1      x_kimjn[0,2,2,2,1]
 BV BND1      x_kimjn[0,2,2,2,2]
 BV BND1      x_kimjn[0,2,2,2,9]
 BV BND1      x_kimjn[0,2,2,2,12]
 BV BND1      x_kimjn[0,2,2,2,10]
 BV BND1      x_kimjn[0,2,2,2,5]
 BV BND1      x_kimjn[0,2,2,2,6]
 BV BND1      x_kimjn[0,2,2,2,7]
 BV BND1      x_kimjn[0,2,2,2,8]
 BV BND1      x_kimjn[0,2,2,2,13]
 BV BND1      x_kimjn[0,2,2,2,0]
 BV BND1      x_kimjn[0,2,2,3,0]
 BV BND1      x_kimjn[0,2,2,4,0]
 BV BND1      x_kimjn[0,2,9,1,17]
 BV BND1      x_kimjn[0,2,9,1,0]
 BV BND1      x_kimjn[0,2,9,2,1]
 BV BND1      x_kimjn[0,2,9,2,2]
 BV BND1      x_kimjn[0,2,9,2,9]
 BV BND1      x_kimjn[0,2,9,2,12]
 BV BND1      x_kimjn[0,2,9,2,10]
 BV BND1      x_kimjn[0,2,9,2,5]
 BV BND1      x_kimjn[0,2,9,2,6]
 BV BND1      x_kimjn[0,2,9,2,7]
 BV BND1      x_kimjn[0,2,9,2,8]
 BV BND1      x_kimjn[0,2,9,2,13]
 BV BND1      x_kimjn[0,2,9,2,0]
 BV BND1      x_kimjn[0,2,9,3,0]
 BV BND1      x_kimjn[0,2,9,4,0]
 BV BND1      x_kimjn[0,2,12,1,17]
 BV BND1      x_kimjn[0,2,12,1,0]
 BV BND1      x_kimjn[0,2,12,2,1]
 BV BND1      x_kimjn[0,2,12,2,2]
 BV BND1      x_kimjn[0,2,12,2,9]
 BV BND1      x_kimjn[0,2,12,2,12]
 BV BND1      x_kimjn[0,2,12,2,10]
 BV BND1      x_kimjn[0,2,12,2,5]
 BV BND1      x_kimjn[0,2,12,2,6]
 BV BND1      x_kimjn[0,2,12,2,7]
 BV BND1      x_kimjn[0,2,12,2,8]
 BV BND1      x_kimjn[0,2,12,2,13]
 BV BND1      x_kimjn[0,2,12,2,0]
 BV BND1      x_kimjn[0,2,12,3,0]
 BV BND1      x_kimjn[0,2,12,4,0]
 BV BND1      x_kimjn[0,2,10,1,17]
 BV BND1      x_kimjn[0,2,10,1,0]
 BV BND1      x_kimjn[0,2,10,2,1]
 BV BND1      x_kimjn[0,2,10,2,2]
 BV BND1      x_kimjn[0,2,10,2,9]
 BV BND1      x_kimjn[0,2,10,2,12]
 BV BND1      x_kimjn[0,2,10,2,10]
 BV BND1      x_kimjn[0,2,10,2,5]
 BV BND1      x_kimjn[0,2,10,2,6]
 BV BND1      x_kimjn[0,2,10,2,7]
 BV BND1      x_kimjn[0,2,10,2,8]
 BV BND1      x_kimjn[0,2,10,2,13]
 BV BND1      x_kimjn[0,2,10,2,0]
 BV BND1      x_kimjn[0,2,10,3,0]
 BV BND1      x_kimjn[0,2,10,4,0]
 BV BND1      x_kimjn[0,2,5,1,17]
 BV BND1      x_kimjn[0,2,5,1,0]
 BV BND1      x_kimjn[0,2,5,2,1]
 BV BND1      x_kimjn[0,2,5,2,2]
 BV BND1      x_kimjn[0,2,5,2,9]
 BV BND1      x_kimjn[0,2,5,2,12]
 BV BND1      x_kimjn[0,2,5,2,10]
 BV BND1      x_kimjn[0,2,5,2,5]
 BV BND1      x_kimjn[0,2,5,2,6]
 BV BND1      x_kimjn[0,2,5,2,7]
 BV BND1      x_kimjn[0,2,5,2,8]
 BV BND1      x_kimjn[0,2,5,2,13]
 BV BND1      x_kimjn[0,2,5,2,0]
 BV BND1      x_kimjn[0,2,5,3,0]
 BV BND1      x_kimjn[0,2,5,4,0]
 BV BND1      x_kimjn[0,2,6,1,17]
 BV BND1      x_kimjn[0,2,6,1,0]
 BV BND1      x_kimjn[0,2,6,2,1]
 BV BND1      x_kimjn[0,2,6,2,2]
 BV BND1      x_kimjn[0,2,6,2,9]
 BV BND1      x_kimjn[0,2,6,2,12]
 BV BND1      x_kimjn[0,2,6,2,10]
 BV BND1      x_kimjn[0,2,6,2,5]
 BV BND1      x_kimjn[0,2,6,2,6]
 BV BND1      x_kimjn[0,2,6,2,7]
 BV BND1      x_kimjn[0,2,6,2,8]
 BV BND1      x_kimjn[0,2,6,2,13]
 BV BND1      x_kimjn[0,2,6,2,0]
 BV BND1      x_kimjn[0,2,6,3,0]
 BV BND1      x_kimjn[0,2,6,4,0]
 BV BND1      x_kimjn[0,2,7,1,17]
 BV BND1      x_kimjn[0,2,7,1,0]
 BV BND1      x_kimjn[0,2,7,2,1]
 BV BND1      x_kimjn[0,2,7,2,2]
 BV BND1      x_kimjn[0,2,7,2,9]
 BV BND1      x_kimjn[0,2,7,2,12]
 BV BND1      x_kimjn[0,2,7,2,10]
 BV BND1      x_kimjn[0,2,7,2,5]
 BV BND1      x_kimjn[0,2,7,2,6]
 BV BND1      x_kimjn[0,2,7,2,7]
 BV BND1      x_kimjn[0,2,7,2,8]
 BV BND1      x_kimjn[0,2,7,2,13]
 BV BND1      x_kimjn[0,2,7,2,0]
 BV BND1      x_kimjn[0,2,7,3,0]
 BV BND1      x_kimjn[0,2,7,4,0]
 BV BND1      x_kimjn[0,2,8,1,17]
 BV BND1      x_kimjn[0,2,8,1,0]
 BV BND1      x_kimjn[0,2,8,2,1]
 BV BND1      x_kimjn[0,2,8,2,2]
 BV BND1      x_kimjn[0,2,8,2,9]
 BV BND1      x_kimjn[0,2,8,2,12]
 BV BND1      x_kimjn[0,2,8,2,10]
 BV BND1      x_kimjn[0,2,8,2,5]
 BV BND1      x_kimjn[0,2,8,2,6]
 BV BND1      x_kimjn[0,2,8,2,7]
 BV BND1      x_kimjn[0,2,8,2,8]
 BV BND1      x_kimjn[0,2,8,2,13]
 BV BND1      x_kimjn[0,2,8,2,0]
 BV BND1      x_kimjn[0,2,8,3,0]
 BV BND1      x_kimjn[0,2,8,4,0]
 BV BND1      x_kimjn[0,2,13,1,17]
 BV BND1      x_kimjn[0,2,13,1,0]
 BV BND1      x_kimjn[0,2,13,2,1]
 BV BND1      x_kimjn[0,2,13,2,2]
 BV BND1      x_kimjn[0,2,13,2,9]
 BV BND1      x_kimjn[0,2,13,2,12]
 BV BND1      x_kimjn[0,2,13,2,10]
 BV BND1      x_kimjn[0,2,13,2,5]
 BV BND1      x_kimjn[0,2,13,2,6]
 BV BND1      x_kimjn[0,2,13,2,7]
 BV BND1      x_kimjn[0,2,13,2,8]
 BV BND1      x_kimjn[0,2,13,2,13]
 BV BND1      x_kimjn[0,2,13,2,0]
 BV BND1      x_kimjn[0,2,13,3,0]
 BV BND1      x_kimjn[0,2,13,4,0]
 BV BND1      x_kimjn[0,2,0,1,17]
 BV BND1      x_kimjn[0,2,0,1,0]
 BV BND1      x_kimjn[0,2,0,2,1]
 BV BND1      x_kimjn[0,2,0,2,2]
 BV BND1      x_kimjn[0,2,0,2,9]
 BV BND1      x_kimjn[0,2,0,2,12]
 BV BND1      x_kimjn[0,2,0,2,10]
 BV BND1      x_kimjn[0,2,0,2,5]
 BV BND1      x_kimjn[0,2,0,2,6]
 BV BND1      x_kimjn[0,2,0,2,7]
 BV BND1      x_kimjn[0,2,0,2,8]
 BV BND1      x_kimjn[0,2,0,2,13]
 BV BND1      x_kimjn[0,2,0,2,0]
 BV BND1      x_kimjn[0,2,0,3,0]
 BV BND1      x_kimjn[0,2,0,4,0]
 BV BND1      x_kimjn[0,3,0,1,17]
 BV BND1      x_kimjn[0,3,0,1,0]
 BV BND1      x_kimjn[0,3,0,2,1]
 BV BND1      x_kimjn[0,3,0,2,2]
 BV BND1      x_kimjn[0,3,0,2,9]
 BV BND1      x_kimjn[0,3,0,2,12]
 BV BND1      x_kimjn[0,3,0,2,10]
 BV BND1      x_kimjn[0,3,0,2,5]
 BV BND1      x_kimjn[0,3,0,2,6]
 BV BND1      x_kimjn[0,3,0,2,7]
 BV BND1      x_kimjn[0,3,0,2,8]
 BV BND1      x_kimjn[0,3,0,2,13]
 BV BND1      x_kimjn[0,3,0,2,0]
 BV BND1      x_kimjn[0,3,0,3,0]
 BV BND1      x_kimjn[0,3,0,4,0]
 BV BND1      x_kimjn[0,4,0,1,17]
 BV BND1      x_kimjn[0,4,0,1,0]
 BV BND1      x_kimjn[0,4,0,2,1]
 BV BND1      x_kimjn[0,4,0,2,2]
 BV BND1      x_kimjn[0,4,0,2,9]
 BV BND1      x_kimjn[0,4,0,2,12]
 BV BND1      x_kimjn[0,4,0,2,10]
 BV BND1      x_kimjn[0,4,0,2,5]
 BV BND1      x_kimjn[0,4,0,2,6]
 BV BND1      x_kimjn[0,4,0,2,7]
 BV BND1      x_kimjn[0,4,0,2,8]
 BV BND1      x_kimjn[0,4,0,2,13]
 BV BND1      x_kimjn[0,4,0,2,0]
 BV BND1      x_kimjn[0,4,0,3,0]
 BV BND1      x_kimjn[0,4,0,4,0]
 BV BND1      xs_kim[0,1,17]
 BV BND1      xs_kim[0,1,0]
 BV BND1      xs_kim[0,2,1]
 BV BND1      xs_kim[0,2,2]
 BV BND1      xs_kim[0,2,9]
 BV BND1      xs_kim[0,2,12]
 BV BND1      xs_kim[0,2,10]
 BV BND1      xs_kim[0,2,5]
 BV BND1      xs_kim[0,2,6]
 BV BND1      xs_kim[0,2,7]
 BV BND1      xs_kim[0,2,8]
 BV BND1      xs_kim[0,2,13]
 BV BND1      xs_kim[0,2,0]
 BV BND1      xe_kjn[0,3,0]
 BV BND1      xe_kjn[0,4,0]
 BV BND1      xod_k[0]
 BV BND1      y_kim[0,1,17]
 BV BND1      y_kim[0,1,0]
 BV BND1      y_kim[0,2,1]
 BV BND1      y_kim[0,2,2]
 BV BND1      y_kim[0,2,9]
 BV BND1      y_kim[0,2,12]
 BV BND1      y_kim[0,2,10]
 BV BND1      y_kim[0,2,5]
 BV BND1      y_kim[0,2,6]
 BV BND1      y_kim[0,2,7]
 BV BND1      y_kim[0,2,8]
 BV BND1      y_kim[0,2,13]
 BV BND1      y_kim[0,2,0]
 BV BND1      y_kim[0,3,0]
 BV BND1      y_kim[0,4,0]
 BV BND1      z_ki[0,1]
 BV BND1      z_ki[0,2]
ENDATA
